FROM alpine:latest

RUN apk update \
    && apk --no-cache --update add build-base

WORKDIR /work

COPY nitro.h .
COPY nitro.c .
COPY nitroctl.c .
COPY Makefile .

RUN make tiny CPPFLAGS=-DREOPEN_USE_DUP_HACK

VOLUME /out

RUN nm --size-sort nitro
RUN ls -l nitro nitroctl
RUN size nitro nitroctl

RUN cp nitro nitroctl /out
