.Dd August 27, 2025
.Dt NITROCTL 1
.Os
.Sh NAME
.Nm nitroctl
.Nd control and manage services monitored by nitro
.Sh SYNOPSIS
.Nm
.Op Fl t Ar timeout
.Ar command
.Ar services\ ...
.Sh DESCRIPTION
.Nm
supports the following commands:
.Pp
.Bl -tag -width 15n -compact
.It Cm list
List all services and information about them (default).
.It Cm scan , Cm rescan
Rescan the service list from the file system.
.It Cm up , Cm u
Request
.Ar services
to be up.
.It Cm down , Cm d
Request
.Ar services
to be down.
.It Cm start
Request
.Ar services
to be up and wait for it to enter
.Dv UP .
.It Cm stop
Request
.Ar services
to be down and wait for it to enter
.Dv DOWN .
.It Cm restart
Request
.Ar services
to be restarted and wait for it to be
.Dv UP
again.
.It Cm fast-start
Request
.Ar services
to be started and wait for it to be in state
.Dv STARTING .
.It Cm fast-stop
Request
.Ar services
to be down and wait for it to be in state
.Dv SHUTDOWN .
.It Cm fast-restart , Cm r
Request
.Ar services
to be restarted and wait for it to be in state
.Dv RESTART .
.It Cm pause , Cm cont , Cm hup , Cm alarm , Cm interrupt , Cm quit , Cm term , Cm kill , Cm 1 , Cm 2
Send the signal to
.Ar services .
The first character can be used as a shortcut.
.It Cm pidof
Print PIDs of the
.Ar services .
.It Cm check
Exit with status 0 if the
.Ar services
are running.
.It Cm Reboot
Request system reboot.
.It Cm Shutdown
Request system shutdown.
.El
.Pp
By default, the
.Ar timeout
is infinite.
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev NITRO_SOCK
The control socket
.Pq by default: Pa /var/run/nitro/nitro.sock
where
.Xr nitro 8
listens for commands.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr nitro 8
.Sh AUTHORS
.An Leah Neukirchen Aq Mt leah@vuxu.org
